import re
import statistics

TRANSITION_WORDS = {
    "furthermore", "moreover", "additionally", "consequently", "therefore",
    "nevertheless", "subsequently", "notably", "significantly", "essentially",
    "ultimately", "specifically", "particularly", "importantly", "however",
    "although", "despite", "regardless", "conversely", "alternatively"
}

_CONTRACTION_RE = re.compile(
    r"\b\w+n't\b|\bi'm\b|\bit's\b|\byou're\b|\bi've\b|\bi'll\b"
    r"|\bwon't\b|\bcan't\b|\bdon't\b|\bthey're\b|\bwe're\b"
    r"|\bhe's\b|\bshe's\b|\bdoesn't\b|\bdidn't\b|\bwouldn't\b"
    r"|\bcouldn't\b|\bshouldn't\b",
    re.IGNORECASE,
)


def burstiness_score(text):
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    if len(sentences) < 2:
        return 0.5
    lengths = [len(s.split()) for s in sentences]
    mean = statistics.mean(lengths)
    if mean == 0:
        return 0.5
    cv = statistics.stdev(lengths) / mean
    # low CV (uniform rhythm) -> score near 1.0 (AI-like)
    # high CV (erratic rhythm) -> score near 0.0 (human-like)
    score = max(0.0, 1.0 - min(cv, 1.0))
    return round(score, 4)


def stylometric_score(text):
    words = re.findall(r"\b\w+\b", text.lower())
    if len(words) < 5:
        return 0.5

    # Feature 1: formal transition word ratio
    # AI text uses transitions like "Furthermore" and "Consequently" at high rates
    transition_count = sum(1 for w in words if w in TRANSITION_WORDS)
    transition_score = min(1.0, (transition_count / len(words)) * 20)

    # Feature 2: contraction absence
    # AI text almost never uses contractions; human casual writing uses them freely
    contraction_count = len(_CONTRACTION_RE.findall(text))
    contraction_score = max(0.0, 1.0 - (contraction_count / len(words)) * 10)

    # Feature 3: sentence capitalization ratio
    # TTR is unreliable at short text lengths; capitalization is stable.
    # AI text consistently capitalizes sentence starts. All-lowercase human writing scores 0.
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    capitalized = sum(1 for s in sentences if s and s[0].isupper())
    cap_score = capitalized / max(len(sentences), 1)

    score = (transition_score + contraction_score + cap_score) / 3.0
    return round(score, 4)


def combine_scores(b_score, s_score):
    return round(0.5 * b_score + 0.5 * s_score, 4)


def generate_label(confidence):
    if confidence >= 0.80:
        return (
            "ai",
            "This content was likely generated by AI. Our system analyzed writing patterns "
            "and detected strong indicators of AI authorship. This label is not a judgment. "
            "It is context for you as a reader.",
        )
    elif confidence <= 0.20:
        return (
            "human",
            "This content appears to be human written. Our system found no strong indicators "
            "of AI generation in the writing patterns it analyzed.",
        )
    else:
        return (
            "uncertain",
            "Our system was unable to make a confident determination about the origin of this "
            "content. The signals were mixed or inconclusive. Treat this label as informational, "
            "not definitive.",
        )
